[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/pasticeri-amanda-backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/products"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 