[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/pasticeri-amanda-backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "pasticeri-amanda-backend"

[[volumes]]
name = "uploads-volume"
mountPath = "/app/uploads" 